const IMAGE = {
    // Menu Tab
    ICON_MENU : require('../image/menu.png'),
    ICON_BACK : require('../image/back.png'),

    ICON_HOME : require('../image/home2.png'),
    ICON_HOME2 : require('../image/home.png'),

    ICON_MAP : require('../image/map2.png'),
    ICON_MAP2 : require('../image/map.png'),

    ICON_NEW_NORMAL : require('../image/new2.png'),
    ICON_NEW_NORMAL2 : require('../image/new.png'),

    ICON_INFO : require('../image/info2.png'),
    ICON_INFO2 : require('../image/info.png'),

    // Tab
    // HomeScreen
        //Symptomp
    IMAGE_SYMPTOMPS1 : require('../image/symptomps1.png'),
    IMAGE_SYMPTOMPS2 : require('../image/symptomps2.png'),
    IMAGE_SYMPTOMPS3 : require('../image/symptomps3.png'),
    IMAGE_SYMPTOMPS4 : require('../image/symptomps4.png'),
    IMAGE_SYMPTOMPS5 : require('../image/symptomps5.png'),
    IMAGE_SYMPTOMPS6 : require('../image/symptomps6.png'),
    IMAGE_SYMPTOMPS7 : require('../image/symptomps7.png'),
    IMAGE_SYMPTOMPS8 : require('../image/symptomps8.png'),
        //Preventtio2
    IMAGE_PREVENTION1 : require('../image/prevention1.png'),
    IMAGE_PREVENTION2 : require('../image/prevention2.png'),
    IMAGE_PREVENTION3 : require('../image/prevention3.png'),
    IMAGE_PREVENTION4 : require('../image/prevention4.png'),
    IMAGE_PREVENTION5 : require('../image/prevention5.png'),
    IMAGE_PREVENTION6 : require('../image/prevention6.png'),
    IMAGE_PREVENTION7 : require('../image/prevention7.png'),
    // Drawer
    // CoviddetailScreen
    IMAGE_COVIDDETAIL : require('../image/covid19detail.png'),

    // OriginCoviddetailScreen
    IMAGE_ORIGIN : require('../image/origin.png'),
    IMAGE_ORIGIN1 : require('../image/origin1.jpg'),
    IMAGE_ORIGIN2 : require('../image/origin2.jpg'),
    IMAGE_ORIGIN3 : require('../image/origin3.png'),
    IMAGE_ORIGIN4 : require('../image/origin4.jpg'),

    //EventCoviddetailScreen
    IMAGE_EVENT : require('../image/event.jpg'),
    //
    IMAGE_TRANS : require('../image/trans.jpg'),
    //
    IMAGE_LOOK : require('../image/look.jpg'),
    //
    IMAGE_LOW : require('../image/low.png'),
    IMAGE_HIGH : require('../image/high.png'),
    //
    IMAGE_CORRECT : require('../image/corret.jpg'),
    //
    IMAGE_HEAL : require('../image/heal.jpg'),
    //
    IMAGE_PHYSICAL : require('../image/physical.jpg'),
    IMAGE_PHYSICAL2 : require('../image/physical2.jpg'),
    //
    IMAGE_EFFECT : require('../image/effect.jpeg'),
    //Agency
    IMAGE_AGENCY1 : require('../image/department1.png'),
    IMAGE_AGENCY2 : require('../image/department2.png'),
    IMAGE_AGENCY3 : require('../image/department3.png'),

    //NEW NORMAL
    IMAGE_HOME : require('../image/house2.jpg'),
    IMAGE_OFFICE : require('../image/office.jpg'),
    IMAGE_HOME2 : require('../image/house.jpg'),
    IMAGE_WEB :require('../image/web.png'),

    IMAGE_AVATAR1 : require('../image/avatar1.png'),
    IMAGE_AVATAR2 : require('../image/avatar2.png'),
    IMAGE_AVATAR3 : require('../image/avatar3.png'),
    IMAGE_AVATAR4 : require('../image/avatar4.png'),
    IMAGE_AVATAR5 : require('../image/avatar5.png'),
    IMAGE_AVATAR6 : require('../image/avatar6.png'),
    IMAGE_AVATAR7 : require('../image/avatar7.png'),
    IMAGE_AVATAR8 : require('../image/avatar8.png'),
    IMAGE_AVATAR9 : require('../image/avatar9.png'),
    IMAGE_AVATAR10: require('../image/avatar10.png'),
    IMAGE_AVATAR11 : require('../image/avatar11.png'),
    IMAGE_AVATAR12 : require('../image/avatar12.png'),
    IMAGE_AVATAR13 : require('../image/avatar13.png'),
    IMAGE_AVATAR14 : require('../image/avatar14.png'),
    IMAGE_AVATAR15 : require('../image/avatar15.png'),
    IMAGE_AVATAR16 : require('../image/avatar16.png'),
    IMAGE_AVATAR17 : require('../image/avatar17.png'),
    IMAGE_AVATAR18 : require('../image/avatar18.png'),
    IMAGE_AVATAR19 : require('../image/avatar19.png'),
    IMAGE_AVATAR20 : require('../image/avatar20.png'),
    IMAGE_AVATAR21 : require('../image/avatar21.png'),
    IMAGE_AVATAR22 : require('../image/avatar22.png'),
    IMAGE_AVATAR23 : require('../image/avatar23.png'),
    IMAGE_AVATAR24 : require('../image/avatar24.png'),
    IMAGE_AVATAR25 : require('../image/avatar25.png'),
    IMAGE_AVATAR26 : require('../image/avatar26.png'),
    IMAGE_AVATAR27 : require('../image/avatar27.png'),
    IMAGE_AVATAR28 : require('../image/avatar28.png'),
    IMAGE_AVATAR29 : require('../image/avatar29.png'),
    IMAGE_AVATAR30 : require('../image/avatar30.png'),
    IMAGE_AVATAR31 : require('../image/avatar31.png'),

    //INfo
    IMAGE_EMER : require('../image/emer.jpg'),
    IMAGE_AGEN : require('../image/agen.jpg'),
    IMAGE_THCHANA : require('../image/thai.png'),

    // โรงพยาบาล
    IMAGE_HOS1 : require('../image/chula.jpg'),
    IMAGE_HOS2 : require('../image/hos2.jpg'),
    IMAGE_HOS3 : require('../image/hos3.jpg'),
    IMAGE_HOS4 : require('../image/hos4.png'),
    IMAGE_HOS5 : require('../image/hos5.jpg'),
    IMAGE_HOS6 : require('../image/hos6.jpg'),
    IMAGE_HOS7 : require('../image/hos7.jpg'),
    IMAGE_HOS8 : require('../image/hos8.jpg'),
    IMAGE_HOS9 : require('../image/hos9.jpg'),
    IMAGE_HOS10 : require('../image/hos10.jpg'),
    IMAGE_HOS11 : require('../image/hos11.jpg'),
    IMAGE_HOS12 : require('../image/hos12.jpg'),
    IMAGE_HOS13 : require('../image/hos13.jpg'),
    IMAGE_HOS14 : require('../image/hos14.png'),
    IMAGE_HOS15 : require('../image/hos15.jpg'),
    IMAGE_HOS16 : require('../image/hos16.jpg'),
    IMAGE_HOS17 : require('../image/hos17.jpg'),
    IMAGE_HOS18 : require('../image/hos18.jpg'),
    // department
    IMAGE_DEP1 : require('../image/dep1.png'),
    IMAGE_DEP2 : require('../image/dep2.png'),
    IMAGE_DEP3 : require('../image/dep3.jpg'),
    IMAGE_DEP4 : require('../image/dep4.png'),
    
    
    //จังหวัด
    IMAGE_BKK : require('../image/bangkok.jpg'),
    IMAGE_CBI : require('../image/chonburi.jpg'),
    IMAGE_CPM : require('../image/phuket.jpg'),
    IMAGE_SPK : require('../image/SamutPrakan.jpg'),
    IMAGE_NBI : require('../image/Nonthaburi.jpg'),
    IMAGE_YLA : require('../image/Yala.png'),
    IMAGE_SKA : require('../image/Songkhla.jpg'),
    IMAGE_PTN : require('../image/Pattani.jpg'),
    IMAGE_NWT : require('../image/Narathiwat.jpeg'),
    IMAGE_CMI : require('../image/ChiangMai.jpg'),
    IMAGE_PTE : require('../image/PathumThani.jpg'),
    IMAGE_CCO : require('../image/Chachoengsao.jpg'),
    IMAGE_NPT : require('../image/NakhonPathom.png'),
    IMAGE_CPN : require('../image/Chumphon.jpg'),
    IMAGE_KBI : require('../image/Krabi.jpg'),
    IMAGE_NMA : require('../image/NakhonRatchasima.jpg'),
    IMAGE_SNI : require('../image/SuratThani.jpg'),
    IMAGE_STN : require('../image/Satun.jpg'),
    IMAGE_PKN : require('../image/Prachuap.jpg'),
    IMAGE_UBN : require('../image/Ubon.jpg'),
    IMAGE_PLG : require('../image/Phatthalung.jpg'),
    IMAGE_SKN : require('../image/SamutSakhon.jpg'),
    IMAGE_BRM : require('../image/Buriram.jpg'),
    IMAGE_NST : require('../image/NST.jpg'),
    IMAGE_UDN : require('../image/Udon.jpg'),
    IMAGE_SKW : require('../image/SaKaeo.jpg'),
    IMAGE_PRI : require('../image/Prachinburi.jpg'),
    IMAGE_KRI : require('../image/Kan.jpg'),
    IMAGE_SRN : require('../image/Surin.jpg'),
    IMAGE_CRI : require('../image/ChiangRai.jpg'),
    IMAGE_NSN : require('../image/NakhonSawan.jpg'),
    IMAGE_SSK : require('../image/Sisaket.jpg'),
    IMAGE_TRG : require('../image/Trang.jpg'),
    IMAGE_RBR : require('../image/Ratchaburi.jpg'),
    IMAGE_PLK : require('../image/Phitsanulok.jpg'),
    IMAGE_KKN : require('../image/KhonKaen.jpg'),
    IMAGE_SPB : require('../image/Suphan.jpg'),
    IMAGE_RYG : require('../image/Rayong.jpg'),
    IMAGE_LEI : require('../image/Loei.jpg'),
    IMAGE_MSN : require('../image/MSN.jpg'),
    IMAGE_SRI : require('../image/Saraburi.jpg'),
    IMAGE_MDH : require('../image/Mukdahan.jpg'),
    IMAGE_AYA : require('../image/AYA.jpg'),
    IMAGE_LPN : require('../image/Lamphun.jpg'),
    IMAGE_LPG : require('../image/Lampang.jpg'),
    IMAGE_PNB : require('../image/Phetchabun.jpg'),
    IMAGE_STI : require('../image/Sukhothai.jpg'),
    IMAGE_UTT : require('../image/Uttaradit.jpg'),
    IMAGE_CTI : require('../image/Chanthaburi.jpg'),
    IMAGE_RET : require('../image/RoiEt.jpg'),
    IMAGE_TAK : require('../image/Tak.jpg'),
    IMAGE_NBP : require('../image/NBP.jpg'),
    IMAGE_NKI : require('../image/NongKhai.jpg'),
    IMAGE_CPM : require('../image/Chaiyaphum.jpg'),
    IMAGE_PYO : require('../image/Phayao.jpg'),
    IMAGE_KSN : require('../image/Kalasin.jpg'),
    IMAGE_NYK : require('../image/NakhonNayok.jpg'),
    IMAGE_ACR : require('../image/ACR.jpg'),
    IMAGE_PNA : require('../image/PhangNga.jpg'),
    IMAGE_LRI : require('../image/Lopburi.jpg'),
    IMAGE_NPT : require('../image/NPT.jpg'),
    IMAGE_PBI : require('../image/Phetchaburi.jpg'),
    IMAGE_PRE : require('../image/Phrae.jpg'),
    IMAGE_YST : require('../image/Yasothon.jpg'),
    IMAGE_UTI : require('../image/Uthai.jpg'),
    IMAGE_SKM : require('../image/Songkhram.jpg'),
    IMAGE_SKN : require('../image/SKN.jpg'),
    IMAGE_MKM : require('../image/MKM.jpg'),

    //drawer
    IMAGE_WHAT : require('../image/question.png'),
    IMAGE_COVID : require('../image/covid-19.png'),
    IMAGE_CALENDAR :require('../image/calendar.png'),
}
export {IMAGE}